# Generated by Django 4.2.6 on 2023-10-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='phone_numver',
            new_name='phone_number',
        ),
    ]
