# Generated by Django 4.2.6 on 2023-10-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['-category_name'], name='category_ca_categor_7bd94b_idx'),
        ),
    ]
